'use client';
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {Chess,Square} from 'chess.js';
type Props={fen:string,selected:Square|null,legal:Square[],last:Square[],onPick:(s:Square)=>void,flipped:boolean,view:number};
function piece(type:string,color:string){const group=new T.Group();const mat=new T.MeshStandardMaterial({color:color==='w'?0xeae5d5:0x343c43,roughness:.29,metalness:.22});const trim=new T.MeshStandardMaterial({color:color==='w'?0xcac1a6:0x68747a,metalness:.65,roughness:.28});
 function mesh(geo:T.BufferGeometry,y:number,material=mat){const m=new T.Mesh(geo,material);m.position.y=y;m.castShadow=true;m.receiveShadow=true;group.add(m);return m;}
 mesh(new T.CylinderGeometry(.32,.35,.12,32),.06);mesh(new T.TorusGeometry(.285,.027,8,32),.13,trim).rotation.x=Math.PI/2;
 const h=type==='p'?.55:type==='k'?.98:type==='q'?.87:.72;
 mesh(new T.LatheGeometry([[.28,0],[.27,.08],[.18,.15],[.12,h*.5],[.15,h*.75],[.22,h*.83],[.22,h*.9]].map(([x,y])=>new T.Vector2(x,y)),32),.14);
 if(type==='p')mesh(new T.SphereGeometry(.19,24,20),h+.14);
 if(type==='r'){mesh(new T.CylinderGeometry(.26,.21,.18,24),h+.1);for(let i=0;i<6;i++){const m=mesh(new T.BoxGeometry(.13,.15,.12),h+.24);m.position.x=Math.cos(i*Math.PI/3)*.21;m.position.z=Math.sin(i*Math.PI/3)*.21;m.rotation.y=-i*Math.PI/3;}}
 if(type==='b'){const m=mesh(new T.SphereGeometry(.2,24,20),h+.2);m.scale.set(.8,1.4,.8);mesh(new T.SphereGeometry(.065,16,12),h+.49);}
 if(type==='q'){mesh(new T.CylinderGeometry(.25,.14,.23,24),h+.15);for(let i=0;i<7;i++){const m=mesh(new T.SphereGeometry(.055,12,10),h+.3);m.position.x=Math.cos(i*Math.PI*2/7)*.22;m.position.z=Math.sin(i*Math.PI*2/7)*.22;}mesh(new T.SphereGeometry(.085,16,12),h+.3);}
 if(type==='k'){mesh(new T.SphereGeometry(.17,20,16),h+.08);mesh(new T.BoxGeometry(.075,.32,.075),h+.35);mesh(new T.BoxGeometry(.25,.075,.075),h+.38);}
 if(type==='n'){const shape=new T.Shape();shape.moveTo(-.18,0);shape.lineTo(.17,0);shape.lineTo(.23,.19);shape.lineTo(.13,.35);shape.lineTo(.12,.53);shape.lineTo(-.01,.47);shape.lineTo(-.23,.29);shape.lineTo(-.28,.13);shape.lineTo(-.08,.14);shape.lineTo(-.18,0);const geo=new T.ExtrudeGeometry(shape,{depth:.23,bevelEnabled:true,bevelSize:.045,bevelThickness:.04,bevelSegments:2,steps:1});geo.translate(0,0,-.115);const m=mesh(geo,h-.05);m.rotation.y=color==='w'?Math.PI/2:-Math.PI/2;}
 return group;}
function ThreeBoard(props:Props){const host=useRef<HTMLDivElement>(null);const current=useRef(props);current.current=props;const state=useRef<any>(null);const [failed,setFailed]=useState(false);
 useEffect(()=>{const el=host.current!;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true});}catch{setFailed(true);return;}renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.setClearColor(0x101719,0);el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive 3D chess board');const scene=new T.Scene();const camera=new T.PerspectiveCamera(38,1,.1,100);camera.position.set(8,11,13);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=10;controls.maxDistance=24;controls.minPolarAngle=.15;controls.maxPolarAngle=Math.PI/2.5;controls.target.set(0,.1,0);scene.add(new T.HemisphereLight(0xe8f0ff,0x29353a,2.3));const light=new T.DirectionalLight(0xfff0d8,3);light.position.set(-4,10,6);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-7,right:7,top:7,bottom:-7});light.shadow.bias=-.001;scene.add(light);const rim=new T.DirectionalLight(0x7fb9cb,2);rim.position.set(5,5,-6);scene.add(rim);
 const base=new T.Mesh(new T.BoxGeometry(8.65,.35,8.65),new T.MeshStandardMaterial({color:0x1b252b,metalness:.55,roughness:.35}));base.position.y=-.25;base.receiveShadow=true;scene.add(base);const edge=new T.Mesh(new T.BoxGeometry(8.72,.05,8.72),new T.MeshStandardMaterial({color:0x9d8651,metalness:.7,roughness:.3}));edge.position.y=-.39;scene.add(edge);
 const squares:T.Mesh[]=[];for(let r=0;r<8;r++)for(let f=0;f<8;f++){const s=new T.Mesh(new T.BoxGeometry(1,.09,1),new T.MeshStandardMaterial({color:(r+f)%2===0?0xaeb7af:0x3f5959,roughness:.6,metalness:.12}));s.position.set(f-3.5,-.045,r-3.5);s.userData.square=('abcdefgh'[f]+(8-r)) as Square;s.receiveShadow=true;scene.add(s);squares.push(s);}
 function label(text:string,x:number,z:number){const c=document.createElement('canvas');c.width=128;c.height=128;const ctx=c.getContext('2d')!;ctx.fillStyle='#b0b8ad';ctx.font='52px Georgia';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,64,64);const texture=new T.CanvasTexture(c);const m=new T.Mesh(new T.PlaneGeometry(.27,.27),new T.MeshBasicMaterial({map:texture,transparent:true}));m.rotation.x=-Math.PI/2;m.position.set(x,-.065,z);scene.add(m);}
 for(let i=0;i<8;i++){label('abcdefgh'[i],i-3.5,4.17);label(String(8-i),-4.17,i-3.5);}
 const pieces=new T.Group(),marks=new T.Group();scene.add(pieces,marks);const ray=new T.Raycaster(),pointer=new T.Vector2();let down={x:0,y:0};const onDown=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY};};const onUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects([...squares,...pieces.children],true);if(hits.length){let ob:T.Object3D|null=hits[0].object;while(ob&&!ob.userData.square)ob=ob.parent;if(ob?.userData.square)current.current.onPick(ob.userData.square);}};renderer.domElement.addEventListener('pointerdown',onDown);renderer.domElement.addEventListener('pointerup',onUp);const ro=new ResizeObserver(()=>{const w=el.clientWidth,h=el.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.fov=T.MathUtils.radToDeg(2*Math.atan(Math.tan(T.MathUtils.degToRad(38)/2)/Math.min(1,w/h)));camera.updateProjectionMatrix();});ro.observe(el);state.current={scene,camera,controls,pieces,marks,squares};let id=0;function frame(){id=requestAnimationFrame(frame);controls.update();renderer.render(scene,camera);}frame();return()=>{cancelAnimationFrame(id);ro.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerdown',onDown);renderer.domElement.removeEventListener('pointerup',onUp);scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{(m as T.MeshBasicMaterial).map?.dispose();m.dispose();});}});renderer.dispose();renderer.domElement.remove();state.current=null;};},[]);
 useEffect(()=>{const s=state.current;if(!s)return;function clear(g:T.Group){while(g.children.length){const o=g.children[0];o.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();if(!Array.isArray(o.material))o.material.dispose();}});g.remove(o);}}clear(s.pieces);clear(s.marks);const game=new Chess(props.fen);game.board().flat().forEach(p=>{if(!p)return;const m=piece(p.type,p.color);m.position.set(p.square.charCodeAt(0)-97-3.5,.03,8-Number(p.square[1])-3.5);m.userData.square=p.square;s.pieces.add(m);});s.squares.forEach((m:T.Mesh)=>{const q=m.userData.square;const f=q.charCodeAt(0)-97,r=8-Number(q[1]);let c=(r+f)%2===0?0xaeb7af:0x3f5959;if(props.last.includes(q))c=(r+f)%2===0?0xb2a570:0x817c4a;if(q===props.selected)c=0xd9b86f;if(game.isCheck()&&game.get(q)?.type==='k'&&game.get(q)?.color===game.turn())c=0xae5550;(m.material as T.MeshStandardMaterial).color.setHex(c);});props.legal.forEach(q=>{const occupied=game.get(q);const m=new T.Mesh(occupied?new T.RingGeometry(.36,.43,32):new T.CircleGeometry(.105,24),new T.MeshBasicMaterial({color:0xf0d699,transparent:true,opacity:.8,side:T.DoubleSide}));m.rotation.x=-Math.PI/2;m.position.set(q.charCodeAt(0)-97-3.5,.018,8-Number(q[1])-3.5);s.marks.add(m);});},[props.fen,props.selected,props.legal.join(','),props.last.join(',')]);
 useEffect(()=>{const s=state.current;if(s){s.camera.position.set(props.flipped?-8:8,11,props.flipped?-13:13);s.controls.target.set(0,.1,0);s.controls.update();}},[props.flipped,props.view]);
 return <><div className="canvas-host" ref={host}/>{failed&&<div className="fallback-message">3D graphics are unavailable on this device. Use the accessible board below.</div>}<details className="accessible-board"><summary>Keyboard / accessible board</summary><div className="flat-board">{new Chess(props.fen).board().map((row,r)=>row.map((p,f)=>{const q=('abcdefgh'[f]+(8-r)) as Square;return <button key={q} onClick={()=>props.onPick(q)} className={`${(r+f)%2?'dark-square':''} ${props.selected===q?'chosen':''}`} aria-label={`${q} ${p?(p.color==='w'?'White':'Black')+' '+({p:'pawn',r:'rook',n:'knight',b:'bishop',q:'queen',k:'king'}[p.type]):'empty'}${props.legal.includes(q)?', legal destination':''}`}>{p?(p.color==='w'?{p:'♙',r:'♖',n:'♘',b:'♗',q:'♕',k:'♔'}[p.type]:{p:'♟',r:'♜',n:'♞',b:'♝',q:'♛',k:'♚'}[p.type]):props.legal.includes(q)?'·':''}<small>{q}</small></button>;}))}</div></details></>;
}
const symbols={w:{p:'♙',r:'♖',n:'♘',b:'♗',q:'♕',k:'♔'},b:{p:'♟',r:'♜',n:'♞',b:'♝',q:'♛',k:'♚'}};
export default function Board(props:Props){
 const [mode,setMode]=useState(localStorage.getItem('board-mode')==='2d'?'2d':'3d');
 const game=new Chess(props.fen);
 const squares=Array.from({length:64},(_,i)=>('abcdefgh'[i%8]+(8-Math.floor(i/8))) as Square);
 if(props.flipped)squares.reverse();
 return <div className="board-surface"><div className="view-switch" role="group" aria-label="Board view">{['2d','3d'].map(value=><button key={value} aria-pressed={mode===value} onClick={()=>{setMode(value);localStorage.setItem('board-mode',value);}}>{value.toUpperCase()}</button>)}</div>{mode==='3d'?<ThreeBoard {...props}/>:<div className="board-2d-frame"><div className="board-2d" aria-label="Interactive 2D chess board">{squares.map(square=>{
 const p=game.get(square),dark=(square.charCodeAt(0)+Number(square[1]))%2===0;
 return <button key={square} className={['tile',dark?'tile-dark':'tile-light',props.selected===square?'tile-selected':'',props.last.includes(square)?'tile-last':'',p?.type==='k'&&p.color===game.turn()&&game.isCheck()?'tile-check':''].join(' ')} onClick={()=>props.onPick(square)} aria-label={square+(p?' '+(p.color==='w'?'White ':'Black ')+({p:'pawn',r:'rook',n:'knight',b:'bishop',q:'queen',k:'king'}[p.type]):' empty')+(props.legal.includes(square)?', legal move':'')} aria-pressed={props.selected===square}><span className={p?.color==='w'?'piece-white':'piece-black'}>{p?symbols[p.color][p.type]:''}</span>{props.legal.includes(square)&&<i className={p?'capture-ring':'move-dot'}/>}<small>{square}</small></button>;
 })}</div></div>}</div>;
}
