import {useEffect,useRef,useState} from 'react';
import {Chess,Square} from 'chess.js';
import Board from './board';
import {Crown,Users,Plus,ArrowRight,Copy,ArrowLeft,FlipVertical2,Maximize2,Minimize2,Mic,MicOff,PhoneOff,Phone,UserPlus,Check,X,Trophy,Wifi,WifiOff,Send} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {MoveHistory,Toast,resultReason} from './match-ui';
import {enterFullscreen,exitFullscreen} from './fullscreen';
import {api,Session} from './api/client';
import {getRealtime} from './api/realtime';
import {VoicePeer} from './api/voice';
import './online.css';
type Match={id:string;code:string;white:string;black:string|null;fen:string;moves:string[];status:string;result:string|null;endReason?:string|null};
type Friend={id:string;name:string;publicId:string};
type Request={_id:string;sender:{name:string;publicId:string}};
export default function Online(){
 const session:Session=JSON.parse(localStorage.getItem('nocturne_session')!);
 const [match,setMatch]=useState<Match|null>(null),[friends,setFriends]=useState<Friend[]>([]),[requests,setRequests]=useState<Request[]>([]),[online,setOnline]=useState<Record<string,boolean>>({});
 const [opponent,setOpponent]=useState<Friend|null>(null);
 const [code,setCode]=useState(''),[friendId,setFriendId]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[invite,setInvite]=useState<any>(null);
 const [selected,setSelected]=useState<Square|null>(null),[promotion,setPromotion]=useState<{from:Square;to:Square}|null>(null),[expanded,setExpanded]=useState(false),[flipped,setFlipped]=useState(false);
 const [confirmJoin,setConfirmJoin]=useState<string|null>(null),[confirmQuit,setConfirmQuit]=useState(false);
 const [friendsOpen,setFriendsOpen]=useState(false),[resultOpen,setResultOpen]=useState(false),[connected,setConnected]=useState(false);
 const finished=useRef<string|null>(null);
 const [incoming,setIncoming]=useState<any>(null),[calling,setCalling]=useState(false),[muted,setMuted]=useState(false);
 const voice=useRef<VoicePeer|null>(null),audio=useRef<HTMLAudioElement>(null),current=useRef(match),board=useRef<HTMLDivElement>(null),pending=useRef<any[]>([]);current.current=match;
 const game=new Chess();match?.moves.forEach(m=>game.move(m));const color=match?.white===session.user.id?'w':'b';const other=match?(color==='w'?match.black:match.white):null;
 function logout(){localStorage.removeItem('nocturne_token');localStorage.removeItem('nocturne_session');location.reload();}
 async function run(fn:()=>Promise<void>){setBusy(true);setNotice('');try{await fn();}catch(e){setNotice(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}
 function save(m:Match){setMatch(m);localStorage.setItem(`match:${session.user.id}`,m.id);}
 async function refresh(){const [f,r]=await Promise.all([api<Friend[]>('/friends'),api<Request[]>('/friends/requests')]);setFriends(f);setRequests(r);getRealtime()?.emit('presence:check',f.map(x=>x.id),(v:Record<string,boolean>)=>setOnline(v));}
 useEffect(()=>{document.body.classList.toggle('board-fullscreen-open',expanded);const exit=()=>{if(!document.fullscreenElement)setExpanded(false);};document.addEventListener('fullscreenchange',exit);return()=>{document.body.classList.remove('board-fullscreen-open');document.removeEventListener('fullscreenchange',exit);};},[expanded]);
 useEffect(()=>{let live=true;const saved=localStorage.getItem(`match:${session.user.id}`);if(saved)void api<Match>(`/matches/${saved}`).then(m=>{if(live)save(m);}).catch(()=>{});void refresh().catch(e=>setNotice(e.message));const timer=setInterval(()=>{void refresh().catch(()=>{});const m=current.current;if(m)void api<Match>(`/matches/${m.id}`).then(value=>{if(live&&current.current?.id===value.id)setMatch(value);}).catch(()=>{});},1500);const expiration=JSON.parse(atob(session.accessToken.split('.')[1])).exp*1000;const expiry=setTimeout(logout,Math.max(0,expiration-Date.now()));return()=>{live=false;clearInterval(timer);clearTimeout(expiry);voice.current?.close();};},[]);
 useEffect(()=>{const timer=setTimeout(()=>{const s=getRealtime();if(!s)return;setConnected(s.connected);s.on('connect',onConnect);s.on('disconnect',onDisconnect);s.on('invite:received',setInvite);s.on('voice:signal',receive);},0);function onConnect(){setConnected(true);}function onDisconnect(){setConnected(false);}async function receive(e:any){const m=current.current;if(!m||m.id!==e.matchId||![m.white,m.black].includes(e.fromUserId))return;if(e.signal.end){endVoice(false);return;}if(e.signal.description?.type==='offer'){setIncoming(e);return;}if(!voice.current){pending.current.push(e.signal);return;}try{await voice.current.receive(e.signal);}catch{setNotice('Voice connection failed. The game can continue.');}}return()=>{clearTimeout(timer);getRealtime()?.off('connect',onConnect);getRealtime()?.off('disconnect',onDisconnect);getRealtime()?.off('invite:received',setInvite);getRealtime()?.off('voice:signal',receive);};},[]);
 function endVoice(notify=true){const m=current.current;if(notify&&m)getRealtime()?.emit('voice:signal',{matchId:m.id,userId:m.white===session.user.id?m.black:m.white,signal:{end:true}});voice.current?.close();voice.current=null;pending.current=[];setCalling(false);setIncoming(null);setMuted(false);}
 async function startVoice(accept=false){await run(async()=>{if(!getRealtime()||!match||!other||!audio.current)return;const peer=new VoicePeer(getRealtime()!,match.id,other,audio.current);voice.current=peer;try{if(accept){await peer.receive(incoming.signal);for(const s of pending.current)await peer.receive(s);pending.current=[];setIncoming(null);}else await peer.call();setCalling(true);}catch(e){endVoice();throw e;}});}
 useEffect(()=>{const s=getRealtime();if(!s||!match)return;const update=(m:Match)=>{if(m.id===current.current?.id)setMatch(m);};const subscribe=()=>s.emit('match:subscribe',{matchId:match.id});s.on('match:updated',update);s.on('connect',subscribe);subscribe();return()=>{s.off('match:updated',update);s.off('connect',subscribe);};},[match?.id]);
 useEffect(()=>{let active=true;setOpponent(null);if(other)void api<Friend>(`/users/${other}`).then(value=>{if(active)setOpponent(value);}).catch(()=>{});return()=>{active=false;};},[other]);
 async function join(c:string){save(await api<Match>('/matches/join',{method:'POST',body:JSON.stringify({code:c.trim().toUpperCase()})}));setInvite(null);setConfirmJoin(null);setNotice('You joined the match. Good luck!');}
 async function move(from:Square,to:Square,promotion='q'){await run(async()=>{const s=getRealtime();if(!s?.connected)throw new Error('Reconnecting. Please try again.');const updated=await new Promise<Match>((resolve,reject)=>s.timeout(7000).emit('match:move',{matchId:match!.id,from,to,promotion},(err:Error|null,value:Match)=>err?reject(new Error('Move not confirmed. Refreshing position.')):resolve(value)));save(updated);setSelected(null);setPromotion(null);});}
 function pick(s:Square){if(busy||promotion||match?.status!=='active'||game.turn()!==color)return;if(selected&&game.moves({square:selected,verbose:true}).some(m=>m.to===s)){if(game.get(selected)?.type==='p'&&['1','8'].includes(s[1]))setPromotion({from:selected,to:s});else void move(selected,s);}else setSelected(game.get(s)?.color===color?s:null);}

 useEffect(()=>{
  if(match?.status==='finished'&&finished.current!==match.id){
   finished.current=match.id;setResultOpen(true);setSelected(null);setPromotion(null);endVoice();
   localStorage.removeItem(`match:${session.user.id}`);
  }
 },[match?.id,match?.status]);
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'&&expanded){void exitFullscreen();setExpanded(false);}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[expanded]);
 async function toggleFullscreen(){if(expanded){await exitFullscreen();setExpanded(false);}else{setExpanded(true);await enterFullscreen(board.current);}}
 async function leave(){endVoice();await exitFullscreen();setExpanded(false);setMatch(null);setSelected(null);setPromotion(null);setResultOpen(false);localStorage.removeItem(`match:${session.user.id}`);}
 function requestLeave(){if(match&&['active','waiting'].includes(match.status))setConfirmQuit(true);else void leave();}
 async function quit(){await run(async()=>{
  if(match)await api(`/matches/${match.id}/quit`,{method:'POST'});
  setConfirmQuit(false);await leave();setNotice('You left the match.');
 });}
 async function inviteFriend(friend:Friend){await run(async()=>{
  let room=match;
  if(!room||room.status!=='waiting'){room=await api<Match>('/matches',{method:'POST'});save(room);}
  if(!getRealtime()?.connected)throw new Error('Reconnect before sending an invitation.');
  getRealtime()?.emit('invite:send',{userId:friend.id,matchId:room.id,code:room.code});
  setNotice(`Invitation sent to ${friend.name}`);setFriendsOpen(false);
 });}
 const myTurn=match?.status==='active'&&game.turn()===color;
 const drawn=match?.result==='1/2-1/2';
 const winner=match?.result==='1-0'?'White':'Black';
 const resultTitle=drawn?'A well-played draw.':`${winner} wins!`;
 const reason=match?.endReason==='resignation'?'Opponent resigned':resultReason(game);
 const pieceSymbols=color==='w'?['♕','♖','♗','♘']:['♛','♜','♝','♞'];
 return <main className="club-page">
  <div className="lobby-heading"><div><span className="eyebrow">THE ONLINE CLUB</span><h1>A worthy opponent awaits.</h1><p>One board. Two minds. Your next great game.</p></div><button className="friends-launch" aria-label="Friends" title="Friends" onClick={()=>setFriendsOpen(true)}><Users size={21}/><span>Friends</span>{requests.length>0&&<b>{requests.length}</b>}</button></div>
  <div className="identity-strip"><span className="identity-avatar">{session.user.name.slice(0,1).toUpperCase()}</span><div><strong>{session.user.name}</strong><small>{session.user.publicId}</small></div><button className="club-icon" title="Copy your user ID" aria-label="Copy your user ID" onClick={()=>void run(async()=>{await navigator.clipboard.writeText(session.user.publicId);setNotice('User ID copied');})}><Copy size={16}/></button><span className={connected?'connection online':'connection'}>{connected?<Wifi size={15}/>:<WifiOff size={15}/>} {connected?'Connected':'Reconnecting'}</span></div>
  {!match?<section className="lobby-options"><div className="create-room"><div className="lobby-art" aria-hidden="true"><span>♞</span><span>♔</span></div><span className="eyebrow">MAKE THE FIRST MOVE</span><h2>Your table. Your invitation.</h2><p>Create a private match and share its code with a friend.</p><button className="primary" disabled={busy} onClick={()=>void run(async()=>{save(await api<Match>('/matches',{method:'POST'}));setNotice('Your table is ready. Share the match code.');})}><Plus size={18}/>Create match</button></div><div className="join-room"><span className="eyebrow">HAVE AN INVITATION?</span><h2>Take your seat.</h2><p>Enter the six-character code from your opponent.</p><form onSubmit={e=>{e.preventDefault();setConfirmJoin(code);}}><label htmlFor="room-code">Match code</label><div className="code-input"><input id="room-code" required minLength={6} maxLength={6} autoComplete="off" placeholder="A B C 1 2 3" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,''))}/><button className="primary" title="Join match" aria-label="Join match" disabled={busy||code.length!==6}><ArrowRight size={21}/></button></div></form><div className="lobby-note"><Users size={20}/><span>Find your friends, see who’s online, and invite them to play.</span></div></div></section>:
  <section ref={board} className={`match-stage ${expanded?'stage-fullscreen':''}`}>
   <div className="match-toolbar"><button className="club-icon" title="Back to lobby" aria-label="Back to lobby" onClick={requestLeave}><ArrowLeft size={19}/></button><span className="match-code">TABLE <strong>{match.code}</strong></span><button className="club-icon" title="Copy match code" aria-label="Copy match code" onClick={()=>void run(async()=>{await navigator.clipboard.writeText(match.code);setNotice('Match code copied');})}><Copy size={17}/></button><div className="toolbar-spacer"/><button className="club-icon" title="Friends" aria-label="Open friends" onClick={()=>setFriendsOpen(true)}><Users size={19}/></button>{other&&match.status!=='finished'&&(calling?<><button className="club-icon" title={muted?'Unmute microphone':'Mute microphone'} aria-label={muted?'Unmute microphone':'Mute microphone'} aria-pressed={muted} onClick={()=>{voice.current?.setMuted(!muted);setMuted(!muted);}}>{muted?<MicOff size={19}/>:<Mic size={19}/>}</button><button className="club-icon danger" title="End voice call" aria-label="End voice call" onClick={()=>endVoice()}><PhoneOff size={19}/></button></>:<button className="club-icon" disabled={busy||!connected} title="Start voice call" aria-label="Start voice call" onClick={()=>void startVoice()}><Phone size={19}/></button>)}<button className="club-icon" title="Flip board" aria-label="Flip board" onClick={()=>setFlipped(!flipped)}><FlipVertical2 size={19}/></button><button className="club-icon" title={expanded?'Exit fullscreen':'Fullscreen'} aria-label={expanded?'Exit fullscreen':'Fullscreen'} onClick={()=>void toggleFullscreen()}>{expanded?<Minimize2 size={19}/>:<Maximize2 size={19}/>}</button></div>
   <div className="match-layout"><div className="match-play">
    <div className={`seat ${match.status==='active'&&!myTurn?'seat-active':''}`}><div className={`seat-piece ${color==='w'?'black':'white'}`}>{color==='w'?'♚':'♔'}</div><div><strong>{opponent?.name||'Waiting for a friend'}</strong><small>{color==='w'?'Black':'White'}</small></div><span className="seat-status">{match.status==='waiting'?'OPEN SEAT':match.status==='finished'?'FINISHED':!myTurn?'THEIR TURN':'WAITING'}</span></div>
    <div className="online-board"><Board fen={match.fen} selected={selected} legal={selected?game.moves({square:selected,verbose:true}).map(m=>m.to):[]} last={game.history({verbose:true}).slice(-1).flatMap(m=>[m.from,m.to])} onPick={pick} flipped={(color==='b')!==flipped} view={0}/></div>
    <div className={`seat ${myTurn?'seat-active':''}`}><div className={`seat-piece ${color==='w'?'white':'black'}`}>{color==='w'?'♔':'♚'}</div><div><strong>You</strong><small>{color==='w'?'White':'Black'}</small></div><span className="seat-status" aria-live="polite">{match.status==='finished'?'FINISHED':myTurn?(game.isCheck()?'YOUR TURN · CHECK':'YOUR TURN'):'WAITING'}</span></div>
   </div><div className="match-sidebar"><div className="turn-banner" aria-live="polite"><span className={`turn-dot ${game.turn()}`}/><div><h2>{match.status==='waiting'?'Your table is ready':match.status==='finished'?resultTitle:myTurn?'Your move.':'Their move.'}</h2><p>{match.status==='waiting'?'Share the code or invite an online friend.':match.status==='finished'?reason:game.isCheck()?'Check — protect the king.':'Take your time. Make it count.'}</p></div></div><MoveHistory moves={match.moves}/>{match.status==='finished'?<button className="primary" onClick={()=>void leave()}><Plus size={17}/>New match</button>:other&&!friends.some(f=>f.id===other)&&<button className="secondary" disabled={!opponent||busy} onClick={()=>void run(async()=>{await api('/friends/requests',{method:'POST',body:JSON.stringify({publicId:opponent!.publicId})});setNotice('Friend request sent');})}><UserPlus size={17}/>Add opponent</button>}</div></div>
   <audio ref={audio} autoPlay playsInline/>
  </section>}
  <Dialog open={friendsOpen} onOpenChange={setFriendsOpen}><DialogContent className="friends-dialog"><DialogTitle>At your table</DialogTitle><DialogDescription>Invite online friends or connect using their user ID.</DialogDescription><form className="friend-search" onSubmit={e=>{e.preventDefault();void run(async()=>{await api('/friends/requests',{method:'POST',body:JSON.stringify({publicId:friendId.trim().toUpperCase()})});setNotice('Friend request sent');setFriendId('');});}}><input aria-label="Friend user ID" required placeholder="User ID · NC-A1B2C3" value={friendId} onChange={e=>setFriendId(e.target.value.toUpperCase())}/><button className="primary" title="Send friend request" aria-label="Send friend request" disabled={busy}><UserPlus size={19}/></button></form><div className="friends-scroll">{requests.map(r=><div className="friend-row" key={r._id}><span className="identity-avatar">{r.sender.name[0]}</span><div><strong>{r.sender.name}</strong><small>Wants to be friends</small></div><button className="club-icon" title="Accept friend request" aria-label={`Accept request from ${r.sender.name}`} disabled={busy} onClick={()=>void run(async()=>{await api(`/friends/requests/${r._id}/accept`,{method:'PATCH'});await refresh();setNotice('Friend request accepted');})}><Check size={19}/></button></div>)}<span className="eyebrow">YOUR FRIENDS · {friends.length}</span>{friends.length===0&&<div className="friends-empty"><Users size={32}/><p>Good games start with good company.</p><small>Share {session.user.publicId} to find your friends.</small></div>}{[...friends].sort((a,b)=>Number(online[b.id]||false)-Number(online[a.id]||false)).map(f=><div className="friend-row" key={f.id}><span className="identity-avatar">{f.name[0]}<i className={online[f.id]?'presence-dot live':'presence-dot'}/></span><div><strong>{f.name}</strong><small>{online[f.id]?'Online':'Offline'} · {f.publicId}</small></div><button className="club-icon" disabled={busy||!online[f.id]||match?.status==='active'} title={online[f.id]?'Invite to match':'Friend is offline'} aria-label={`Invite ${f.name}`} onClick={()=>void inviteFriend(f)}><Send size={18}/></button></div>)}</div></DialogContent></Dialog>
  <Dialog open={!!promotion} onOpenChange={open=>{if(!open)setPromotion(null);}}><DialogContent><DialogTitle>Choose your promotion</DialogTitle><DialogDescription>Your pawn has reached the final rank.</DialogDescription><div className="promotion">{['q','r','b','n'].map((p,i)=><button key={p} disabled={busy} onClick={()=>promotion&&void move(promotion.from,promotion.to,p)}><span>{pieceSymbols[i]}</span>{['Queen','Rook','Bishop','Knight'][i]}</button>)}</div></DialogContent></Dialog>
  <Dialog open={resultOpen} onOpenChange={setResultOpen}><DialogContent className="result-dialog"><div className="result-trophy"><Trophy size={40}/></div><DialogTitle>{resultTitle}</DialogTitle><DialogDescription>{reason}. {drawn?'Both players share the result.':`${match?.result===(color==='w'?'1-0':'0-1')?'You':opponent?.name||'Your opponent'} won the match.`}</DialogDescription><div className="result-score">{match?.result}</div><div className="dialog-actions"><button className="secondary" onClick={()=>setResultOpen(false)}>Review board</button><button className="primary" onClick={()=>void leave()}>Back to lobby</button></div></DialogContent></Dialog>
  <Dialog open={!!invite} onOpenChange={open=>{if(!open)setInvite(null);}}><DialogContent><DialogTitle>A seat is waiting for you</DialogTitle><DialogDescription>{invite?.from.publicId} invited you to table {invite?.code}.</DialogDescription><div className="dialog-actions"><button className="secondary" onClick={()=>{getRealtime()?.emit('invite:respond',{userId:invite.from.userId,matchId:invite.matchId,accepted:false});setInvite(null);}}>Decline</button><button className="primary" disabled={busy||match?.status==='active'} onClick={()=>{setConfirmJoin(invite.code);setInvite(null);}}>Join match</button></div>{match?.status==='active'&&<p>Finish your current match before joining another.</p>}</DialogContent></Dialog>
  <Dialog open={!!incoming} onOpenChange={open=>{if(!open)endVoice();}}><DialogContent><DialogTitle>Incoming voice call</DialogTitle><DialogDescription>{opponent?.name||'Your opponent'} would like to talk.</DialogDescription><div className="dialog-actions"><button className="secondary" onClick={()=>endVoice()}><PhoneOff size={18}/>Decline</button><button className="primary" disabled={busy} onClick={()=>void startVoice(true)}><Phone size={18}/>Accept</button></div></DialogContent></Dialog>
  <Dialog open={!!confirmJoin} onOpenChange={open=>{if(!open&&!busy)setConfirmJoin(null);}}><DialogContent><DialogTitle>Join this match?</DialogTitle><DialogDescription>You’re about to join table {confirmJoin}. Ready to play?</DialogDescription><div className="dialog-actions"><button className="secondary" disabled={busy} onClick={()=>setConfirmJoin(null)}>Cancel</button><button className="primary" disabled={busy} onClick={()=>confirmJoin&&void run(()=>join(confirmJoin))}>{busy?'Joining…':'Confirm join'}</button></div></DialogContent></Dialog>
  <Dialog open={confirmQuit} onOpenChange={open=>{if(!open&&!busy)setConfirmQuit(false);}}><DialogContent><DialogTitle>Quit this match?</DialogTitle><DialogDescription>{match?.status==='waiting'?'This will close your waiting room. If an opponent joins before you leave, they will win by resignation.':'Your opponent will win by resignation and the match will end.'}</DialogDescription><div className="dialog-actions"><button className="secondary" disabled={busy} onClick={()=>setConfirmQuit(false)}>Keep playing</button><button className="primary" disabled={busy} onClick={()=>void quit()}>{busy?'Leaving…':'Quit match'}</button></div></DialogContent></Dialog>
  <Toast message={notice} onClose={()=>setNotice('')}/>
 </main>;
}
