'use client';
import { useEffect, useRef, useState } from 'react';
import { Chess, Square } from 'chess.js';
import { Volume2, VolumeX, RotateCcw, RefreshCw, FlipVertical2, Crown, Maximize2 } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import Board from './board';
import ChessWorker from './chess.worker?worker';
import { chooseMove } from './engine.mjs';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
const names: Record<string,string>={p:'Pawn',r:'Rook',n:'Knight',b:'Bishop',q:'Queen',k:'King'};
const glyph: Record<string,string>={p:'♟',r:'♜',n:'♞',b:'♝',q:'♛',k:'♚'};
export default function Home(){
 const game=useRef(new Chess()); const [fen,setFen]=useState(game.current.fen());const [selected,setSelected]=useState<Square|null>(null);const [sound,setSound]=useState(true);const [flipped,setFlipped]=useState(false);const [view,setView]=useState(0);const [promotion,setPromotion]=useState<{from:Square,to:Square}|null>(null);const [reset,setReset]=useState(false);const [notice,setNotice]=useState('Select a piece to see its legal moves.');const audio=useRef<AudioContext|null>(null);
 const [mode,setMode]=useState('computer');const [human,setHuman]=useState('w');const [difficulty,setDifficulty]=useState('medium');const [draftMode,setDraftMode]=useState('computer');const [draftHuman,setDraftHuman]=useState('w');const [draftDifficulty,setDraftDifficulty]=useState('medium');const [retry,setRetry]=useState(0);const [aiError,setAiError]=useState(false);const settings=useRef({mode,human,sound});settings.current={mode,human,sound};
 const g=game.current;const history=g.history({verbose:true});const last=history.at(-1);const legal=selected?g.moves({square:selected,verbose:true}).map(m=>m.to):[];
 function tone(capture=false,check=false){if(!settings.current.sound)return;try{const a=audio.current??(audio.current=new AudioContext());void a.resume();[0,...(check?[.13,.26]:[])].forEach((delay,i)=>{const o=a.createOscillator(),v=a.createGain();o.type=capture?'triangle':'sine';o.frequency.setValueAtTime(check?440+i*110:capture?180:520,a.currentTime+delay);o.frequency.exponentialRampToValueAtTime(capture?70:260,a.currentTime+delay+.12);v.gain.setValueAtTime(.0001,a.currentTime+delay);v.gain.exponentialRampToValueAtTime(.16,a.currentTime+delay+.008);v.gain.exponentialRampToValueAtTime(.0001,a.currentTime+delay+.18);o.connect(v);v.connect(a.destination);o.start(a.currentTime+delay);o.stop(a.currentTime+delay+.2);});}catch{}}
 function move(from:Square,to:Square,p='q',computer=false){if(g.isGameOver())return {error:'The game is over.'};if(!computer&&settings.current.mode==='computer'&&g.turn()!==settings.current.human)return {error:'Wait for the computer to move.'};try{const m=g.move({from,to,promotion:p});setFen(g.fen());setSelected(null);setPromotion(null);setNotice(`${names[m.piece]} ${from} → ${to}${m.captured?' · '+names[m.captured]+' captured':''}`);tone(!!m.captured,g.isCheck());return {san:m.san,fen:g.fen()};}catch{return {error:'That move is not legal.'};}}
 function pick(s:Square){if(g.isGameOver()||promotion||(mode==='computer'&&g.turn()!==human))return;if(selected&&legal.includes(s)){if(g.get(selected)?.type==='p'&&(s[1]==='8'||s[1]==='1'))setPromotion({from:selected,to:s});else move(selected,s);return;}if(g.get(s)?.color===g.turn())setSelected(s===selected?null:s);else setSelected(null);}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();const tools=[{name:'read_chess_position',description:'Read the current chess position and legal moves.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({fen:g.fen(),legalMoves:g.moves(),history:g.history()})},{name:'make_chess_move',description:'Play a legal chess move on the visible board.',inputSchema:{type:'object',properties:{from:{type:'string'},to:{type:'string'},promotion:{type:'string',enum:['q','r','b','n']}},required:['from','to'],additionalProperties:false},execute:(i:any)=>{if(g.isGameOver())return {error:'The game is over.'};if(!/^[a-h][1-8]$/.test(i.from)||!/^[a-h][1-8]$/.test(i.to))return {error:'Invalid square.'};return move(i.from,i.to,i.promotion||'q');}}];tools.forEach(t=>{try{Promise.resolve(context.registerTool(t,{signal:life.signal})).catch(()=>{});}catch{}});return()=>life.abort();},[sound]);
 const computerTurn=mode==='computer'&&g.turn()!==human&&!g.isGameOver();
 useEffect(()=>{
  if(!computerTurn||reset)return;
  let cancelled=false,finished=false,worker:Worker|undefined,watchdog:ReturnType<typeof setTimeout>|undefined;
  setAiError(false);const startFen=g.fen();
  const active=()=>!cancelled&&!finished&&g.fen()===startFen;
  const finish=(m:{from:Square;to:Square;promotion?:string}|null)=>{
   if(!active())return;
   finished=true;clearTimeout(watchdog);worker?.terminate();
   if(!m){setAiError(true);return;}
   const result=move(m.from,m.to,m.promotion||'q',true);if('error' in result)setAiError(true);
  };
  const fallback=()=>{if(!active())return;clearTimeout(watchdog);worker?.terminate();try{finish(chooseMove(startFen,difficulty,200));}catch{const legalMove=g.moves({verbose:true})[0];finish(legalMove||null);}};
  const timer=setTimeout(()=>{try{
   worker=new ChessWorker();worker.onmessage=(event)=>{if(!active())return;if(event.data.move)finish(event.data.move);else fallback();};
   worker.onerror=(event)=>{event.preventDefault();fallback();};worker.onmessageerror=fallback;
   watchdog=setTimeout(fallback,4500);worker.postMessage({fen:startFen,difficulty});
  }catch{fallback();}},350);
  return()=>{cancelled=true;clearTimeout(timer);clearTimeout(watchdog);worker?.terminate();};
 },[fen,mode,human,difficulty,reset,retry]);
 function undo(){g.undo();if(mode==='computer'&&g.turn()!==human&&g.history().length)g.undo();setFen(g.fen());setSelected(null);setPromotion(null);setAiError(false);setNotice('Your last turn was undone.');}
 function openSettings(){setDraftMode(mode);setDraftHuman(human);setDraftDifficulty(difficulty);setReset(true);}
 function newGame(){g.reset();setMode(draftMode);setHuman(draftHuman);setDifficulty(draftDifficulty);setFlipped(draftMode==='computer'&&draftHuman==='b');setFen(g.fen());setSelected(null);setPromotion(null);setReset(false);setAiError(false);setNotice(draftMode==='computer'?'You play '+(draftHuman==='w'?'White. Your move.':'Black. The computer opens.'):'A fresh board. White moves first.');}
 function label(color:string){return mode==='computer'?(human===color?'You':'Computer'):(color==='w'?'Player 01':'Player 02');}
 const turn=g.turn()==='w'?'White':'Black';const status=g.isCheckmate()?`${turn==='White'?'Black':'White'} wins by checkmate`:g.isStalemate()?'Draw by stalemate':g.isThreefoldRepetition()?'Draw by repetition':g.isInsufficientMaterial()?'Draw · insufficient material':g.isDraw()?'Game drawn':computerTurn?(aiError?'Computer paused':'Computer thinking…'):`${turn} to move`;
 function captured(color:string){return history.filter(m=>m.color===color&&m.captured).map(m=>glyph[m.captured!]).join(' ');}
 return <main><header><a className="brand" href="/" aria-label="Nocturne Chess home"><Crown size={30}/><span>NOCTURNE<span className="brand-sub">CHESS CLUB</span></span></a><div className="header-note">A little quiet. A better move.</div><button className="icon-btn" onClick={()=>setSound(!sound)} aria-label={sound?'Mute sound':'Enable sound'} title={sound?'Mute sound':'Enable sound'}>{sound?<Volume2 size={20}/>:<VolumeX size={20}/>}</button></header>
 <div className="workspace"><section className="arena"><div className="arena-title"><div><span className="eyebrow">THE BOARD IS YOURS</span><h1>Your next move.</h1></div><span className="mode">{mode==='computer'?'VS COMPUTER · '+difficulty.toUpperCase():'LOCAL · TWO PLAYERS'}</span></div>
 <div className={`player top ${g.turn()==='b'&&!g.isGameOver()?'active':''}`}><div className="avatar black">♚</div><div><strong>Black <span className="who">· {label('b')}</span></strong><div className="captures">{captured('b')||'All pieces on the board'}</div></div><span className="player-label">{g.turn()==='b'&&!g.isGameOver()?(mode==='computer'&&human!=='b'?'THINKING':'YOUR TURN'):label('b').toUpperCase()}</span></div>
 <div className="board-wrap"><Board fen={fen} selected={selected} legal={legal} last={last?[last.from,last.to]:[]} onPick={pick} flipped={flipped} view={view}/><div className="board-controls"><button onClick={()=>setFlipped(!flipped)} title="Flip board" aria-label="Flip board"><FlipVertical2 size={17}/></button><button onClick={()=>setView(view+1)} title="Reset camera" aria-label="Reset camera"><Maximize2 size={17}/></button></div></div>
 <div className={`player ${g.turn()==='w'&&!g.isGameOver()?'active':''}`}><div className="avatar white">♔</div><div><strong>White <span className="who">· {label('w')}</span></strong><div className="captures">{captured('w')||'All pieces on the board'}</div></div><span className="player-label">{g.turn()==='w'&&!g.isGameOver()?(mode==='computer'&&human!=='w'?'THINKING':'YOUR TURN'):label('w').toUpperCase()}</span></div><p className="gesture">Click a piece, then a square. Drag to orbit · Scroll or pinch to zoom</p></section>
 <aside><div className="game-status"><div className="match-heading"><span className="eyebrow">{mode==='computer'?'PLAY COMPUTER':'FRIENDLY MATCH'}</span><button className="change-mode" onClick={openSettings}>Change mode</button></div><div className="status-row"><span className={`turn-dot ${g.turn()}`}/><h2 aria-live="polite">{status}</h2></div><p>{g.isCheck()&&!g.isCheckmate()?'Check! Protect your king.':g.isGameOver()?'A good game. Ready for another?':'Take your time. Make it count.'}</p></div>
 {aiError&&computerTurn&&<button className="secondary retry" onClick={()=>setRetry(retry+1)}>Retry computer move</button>}<div className="history-title"><h3>Move history</h3><span>{history.length} plies</span></div><div className="history-head"><span>#</span><span>WHITE</span><span>BLACK</span></div><div className="move-list">{history.length?Array.from({length:Math.ceil(history.length/2)},(_,i)=><div className="move-row" key={i}><span>{i+1}.</span><span>{history[i*2]?.san}</span><span className={i*2+1===history.length-1?'latest':''}>{history[i*2+1]?.san||'—'}</span></div>):<div className="empty"><Crown size={35} strokeWidth={1}/><strong>Every game begins<br/>with a possibility.</strong><p>White makes the first move.</p></div>}</div>
 <div className="match-actions"><button className="secondary" disabled={!history.length||(mode==='computer'&&human==='b'&&history.length===1)} onClick={undo}><RotateCcw size={17}/>Undo move</button><button className="primary" onClick={openSettings}><RefreshCw size={17}/>New game</button></div><div className="tip"><span className="eyebrow">AT THE TABLE</span><p aria-live="polite">{notice}</p><div className="legend"><span><i className="legal-dot"/>Legal move</span><span><i className="last-dot"/>Last move</span></div></div></aside></div>
 <footer><span>NOCTURNE / 01</span><span>Classic rules. A new perspective.</span><span>REACT · 3D CHESS</span></footer>
 <Dialog open={!!promotion} onOpenChange={v=>{if(!v)setPromotion(null);}}><DialogContent><DialogTitle>Choose your promotion</DialogTitle><DialogDescription>Your pawn has reached the final rank.</DialogDescription><div className="promotion">{['q','r','b','n'].map(p=><button key={p} onClick={()=>promotion&&move(promotion.from,promotion.to,p)}><span>{glyph[p]}</span>{names[p]}</button>)}</div></DialogContent></Dialog>
 <Dialog open={reset} onOpenChange={setReset}><DialogContent><DialogTitle>Set up a new game</DialogTitle><DialogDescription>Choose an opponent. Starting will clear the current game.</DialogDescription><fieldset className="settings-field"><legend>Play mode</legend><RadioGroup value={draftMode} onValueChange={setDraftMode} className="option-grid">{[['computer','Play computer'],['local','Two players']].map(([v,l])=><label key={v} className={draftMode===v?'option checked':'option'}><RadioGroupItem value={v}/>{l}</label>)}</RadioGroup></fieldset>{draftMode==='computer'&&<><fieldset className="settings-field"><legend>Your pieces</legend><RadioGroup value={draftHuman} onValueChange={setDraftHuman} className="option-grid">{[['w','White · first move'],['b','Black']].map(([v,l])=><label key={v} className={draftHuman===v?'option checked':'option'}><RadioGroupItem value={v}/>{l}</label>)}</RadioGroup></fieldset><fieldset className="settings-field"><legend>Difficulty</legend><RadioGroup value={draftDifficulty} onValueChange={setDraftDifficulty} className="option-grid three">{['easy','medium','hard'].map(v=><label key={v} className={draftDifficulty===v?'option checked':'option'}><RadioGroupItem value={v}/>{v[0].toUpperCase()+v.slice(1)}</label>)}</RadioGroup><p className="difficulty-note">{draftDifficulty==='easy'?'A relaxed opponent, with occasional mistakes.':draftDifficulty==='medium'?'Looks ahead and weighs material and position.':'A deeper search for a tougher casual game.'}</p></fieldset></>}<div className="dialog-actions"><button className="secondary" onClick={()=>setReset(false)}>Cancel</button><button className="primary" onClick={newGame}>Start game</button></div></DialogContent></Dialog>
 </main>;
}
